-- Migration: Add partner services and invoices tables
-- Description: Allows partners to manage their own services/pricing and generate invoices
-- Date: 2026-02-24

-- ============================================
-- PARTNER SERVICES TABLE
-- ============================================
-- Partners can create and manage their own services with custom pricing
CREATE TABLE IF NOT EXISTS partner_services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    depot_id UUID NOT NULL REFERENCES depots(id) ON DELETE CASCADE,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    category VARCHAR(50) NOT NULL CHECK (category IN ('laundry', 'dry-cleaning', 'specialty')),
    price DECIMAL(10, 2) NOT NULL CHECK (price > 0),
    unit VARCHAR(20) NOT NULL CHECK (unit IN ('lb', 'item')),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for efficient querying
CREATE INDEX idx_partner_services_depot_id ON partner_services(depot_id);
CREATE INDEX idx_partner_services_category ON partner_services(category);
CREATE INDEX idx_partner_services_is_active ON partner_services(is_active);

-- Add RLS (Row Level Security) policies
ALTER TABLE partner_services ENABLE ROW LEVEL SECURITY;

-- Policy: Partners can view their own depot's services
CREATE POLICY partner_services_select_policy ON partner_services
    FOR SELECT
    USING (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid()
        )
    );

-- Policy: Partners can insert services for their depot
CREATE POLICY partner_services_insert_policy ON partner_services
    FOR INSERT
    WITH CHECK (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid() AND role = 'partner'
        )
    );

-- Policy: Partners can update their depot's services
CREATE POLICY partner_services_update_policy ON partner_services
    FOR UPDATE
    USING (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid() AND role = 'partner'
        )
    );

-- Policy: Partners can delete their depot's services
CREATE POLICY partner_services_delete_policy ON partner_services
    FOR DELETE
    USING (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid() AND role = 'partner'
        )
    );

-- Policy: Admins can do everything
CREATE POLICY partner_services_admin_policy ON partner_services
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- ============================================
-- PARTNER INVOICES TABLE
-- ============================================
-- Store invoices generated by partners for orders
CREATE TABLE IF NOT EXISTS partner_invoices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    depot_id UUID NOT NULL REFERENCES depots(id) ON DELETE CASCADE,
    order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    customer_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(20),
    customer_email VARCHAR(255),
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    subtotal DECIMAL(10, 2) NOT NULL DEFAULT 0,
    tax DECIMAL(10, 2) NOT NULL DEFAULT 0,
    total DECIMAL(10, 2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'paid', 'overdue')),
    issued_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    due_date TIMESTAMP WITH TIME ZONE,
    paid_date TIMESTAMP WITH TIME ZONE,
    sms_sent BOOLEAN DEFAULT false,
    sms_sent_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes for efficient querying
CREATE INDEX idx_partner_invoices_depot_id ON partner_invoices(depot_id);
CREATE INDEX idx_partner_invoices_order_id ON partner_invoices(order_id);
CREATE INDEX idx_partner_invoices_customer_id ON partner_invoices(customer_id);
CREATE INDEX idx_partner_invoices_status ON partner_invoices(status);
CREATE INDEX idx_partner_invoices_invoice_number ON partner_invoices(invoice_number);
CREATE INDEX idx_partner_invoices_issued_date ON partner_invoices(issued_date);
CREATE INDEX idx_partner_invoices_due_date ON partner_invoices(due_date);

-- Add RLS (Row Level Security) policies
ALTER TABLE partner_invoices ENABLE ROW LEVEL SECURITY;

-- Policy: Partners can view their depot's invoices
CREATE POLICY partner_invoices_select_policy ON partner_invoices
    FOR SELECT
    USING (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid()
        )
        OR
        customer_id = auth.uid()
    );

-- Policy: Partners can create invoices for their depot
CREATE POLICY partner_invoices_insert_policy ON partner_invoices
    FOR INSERT
    WITH CHECK (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid() AND role = 'partner'
        )
    );

-- Policy: Partners can update their depot's invoices
CREATE POLICY partner_invoices_update_policy ON partner_invoices
    FOR UPDATE
    USING (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid() AND role = 'partner'
        )
    );

-- Policy: Partners can delete their depot's invoices
CREATE POLICY partner_invoices_delete_policy ON partner_invoices
    FOR DELETE
    USING (
        depot_id IN (
            SELECT depot_id FROM users WHERE id = auth.uid() AND role = 'partner'
        )
    );

-- Policy: Admins can do everything
CREATE POLICY partner_invoices_admin_policy ON partner_invoices
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin'
        )
    );

-- ============================================
-- TRIGGERS FOR UPDATED_AT
-- ============================================
-- Auto-update updated_at timestamp on record changes

-- Trigger for partner_services
CREATE OR REPLACE FUNCTION update_partner_services_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER partner_services_updated_at_trigger
    BEFORE UPDATE ON partner_services
    FOR EACH ROW
    EXECUTE FUNCTION update_partner_services_updated_at();

-- Trigger for partner_invoices
CREATE OR REPLACE FUNCTION update_partner_invoices_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER partner_invoices_updated_at_trigger
    BEFORE UPDATE ON partner_invoices
    FOR EACH ROW
    EXECUTE FUNCTION update_partner_invoices_updated_at();

-- ============================================
-- COMMENTS FOR DOCUMENTATION
-- ============================================
COMMENT ON TABLE partner_services IS 'Custom services created by partners with their own pricing';
COMMENT ON TABLE partner_invoices IS 'Invoices generated by partners for completed orders';

COMMENT ON COLUMN partner_services.category IS 'Service category: laundry, dry-cleaning, or specialty';
COMMENT ON COLUMN partner_services.unit IS 'Pricing unit: lb (pounds) or item';
COMMENT ON COLUMN partner_invoices.items IS 'JSON array of invoice line items with service_name, quantity, unit_price, total';
COMMENT ON COLUMN partner_invoices.status IS 'Invoice status: draft, sent, paid, or overdue';
COMMENT ON COLUMN partner_invoices.sms_sent IS 'Whether SMS notification was sent to customer';
